package ais.input;

public enum InputDiagnosticCode {
    INVALID_LOG_LINE,
    UNSUPPORTED_NMEA_SENTENCE,
    INVALID_NMEA_FORMAT,
    CHECKSUM_MISSING,
    CHECKSUM_INVALID,
    INVALID_FRAGMENT,
    INCOMPLETE_FRAGMENT,
    DECODE_FAILED,
    INVALID_MMSI,
    INVALID_POSITION,
    DUPLICATE,
    UNSUPPORTED_MESSAGE_TYPE,
    OUTSIDE_SELECTED_DAY,
    SOURCE_OVERFLOW,
    SOURCE_READ_FAILED
}
